# Generated by Django 4.1.5 on 2023-01-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва принтеру')),
                ('api_key', models.CharField(max_length=200, unique=True)),
                ('check_type', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('CLIENT', 'Client')], max_length=200, verbose_name='Тип чеку')),
                ('point_id', models.IntegerField(verbose_name='Назва точки')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтери',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('CLIENT', 'Client')], max_length=200, verbose_name='Тип чеку')),
                ('order', models.JSONField(default=dict, verbose_name='Інформація про замовлення')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RENDERED', 'Rendered'), ('PRINTED', 'Printed')], max_length=200, verbose_name='Статус чеку')),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.printer')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
